version: 2
updates:
  - package-ecosystem: "terraform"
    directories:
      - iac/tf
      - "/"
    ignore:
      - dependency-name: "*-ext-*"
    commit-message:
      prefix: "Terraform"
    target-branch: "main"
    schedule:
      interval: weekly
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
       updates:
          applies-to: version-updates
          patterns:
            - "*"
    open-pull-requests-limit: 1
