############################################################
### AWS ###
# Uncomment the following block if you are using AWS
############################################################
# Use first block in case shared s3 bucket for all environments reports is used.
region: <AWS_DEFAULT_REGION>                       # * can be skipped IF region per environment defined. used for role assumption
accountId: <DEFAULT_AWS_ACCOUNT_ID>                # * can be skipped IF accountId per environment defined
awsPartition: <ROLE_USED_FOR_STACK_DEPLOYMENT>     # * can be skipped IF awsRoleName or Arn per environment is defined. If defined, arn generated: "arn:${awsPartition}:iam::${accountId}:role/${awsRoleName}", default value: "aws"
awsRoleName: <ROLE_USED_FOR_STACK_DEPLOYMENT>      # * can be skipped IF awsRoleName or Arn per environment is defined. If awsRoleName is defined, arn generated: "arn:${awsPartition}:iam::${accountId}:role/${awsRoleName"
awsRoleArn: <ROLE_ARN_USED_FOR_STACK_DEPLOYMENT>   # * can be skipped IF awsRoleName or Arn per environment is defined. If defined, used instead awsRoleName
s3BucketName: <S3_BUCKET_NAME>                     # * can be skipped IF s3BucketName per environment is defined.

# Use environment block if different s3 buckets per environment are used.
dev:                                                 # lowercase environment name, i.e. dev, sit, uat, prod
  accountId: <DEFAULT_AWS_ACCOUNT_ID>                # OPTIONAL. can be skipped IF global accountId is defined
  region: <AWS_DEFAULT_REGION_PER_ENV>               # OPTIONAL. If defined, used for role assumption and later instead global region
  awsPartition: <ROLE_USED_FOR_STACK_DEPLOYMENT>     # OPTIONAL. If defined, arn generated: "arn:${awsPartition}:iam::${accountId}:role/${awsRoleName}", default value: "aws"
  awsRoleName: <ROLE_USED_FOR_STACK_DEPLOYMENT>      # OPTIONAL. can be skipped IF Arn is defined. If awsRoleName is defined, arn generated: "arn:${awsPartition}:iam::${accountId}:role/${awsRoleName"
  awsRoleArn: <ROLE_ARN_USED_FOR_STACK_DEPLOYMENT>   # OPTIONAL. If defined, used instead awsRoleName
  s3BucketName: <S3_BUCKET_NAME>

sit:

prod:

############################################################
### Azure ###
# Uncomment the following block if you are using Azure
############################################################
# # Use first block in case shared storage account for all environments reports is used.
# azureStorageAccountName: <STORAGE_ACCOUNT_NAME>   # * can be skipped IF azureStorageAccountName per environment is defined.
# azureStorageContainerName: <STORAGE_CONTAINER_NAME>     # * can be skipped IF azureStorageContainerName per environment is defined.

# # Use environment block if different storage accounts per environment are used.
# dev:                                              # lowercase environment name, i.e. dev, sit, uat, prod
#   azureStorageAccountName: <STORAGE_ACCOUNT_NAME_FOR_DEV>     # * OPTIONAL. can be skipped IF global azureStorageAccountName is defined
#   azureStorageContainerName: <STORAGE_CONTAINER_NAME_FOR_DEV>       # * OPTIONAL. can be skipped IF global azureStorageContainerName is defined

# sit:

# prod:


############################################################
### GCP ###
# Uncomment the following block if you are using GCP
############################################################
# # Use first block in case shared storage bucket for all environments reports is used.
# gcpBucketName: <STORAGE_BUCKET_NAME>  # E.g., mmcg-did-clmgmt-state-bucket .. Can be skipped IF gcpBucketName per environment is defined.
# gcpBucketPath: <STORAGE_BUCKET_PATH>  # E.g., gha-path .. Can be skipped IF gcpBucketPath per environment is defined.

# # Use environment block if different storage accounts per environment are used.
# dev:                                    # lowercase environment name, i.e. dev, sit, uat, prod
#   gcpBucketName: <STORAGE_BUCKET_NAME>  # * OPTIONAL. can be skipped IF global gcpBucketName is defined
#   gcpBucketPath: <STORAGE_BUCKET_PATH>  # * OPTIONAL. can be skipped IF global gcpBucketPath is defined

# sit:

# prod:
